package under.ground.components.ua;

/**
 * 
 * @author A.Zapotochnyy
 * 
 */

public enum StationsNames {

	//0-15 Blue line
	//16-33 Red
	//34-49 Green
	
	GEROYIV_DNIPRA,MINSKA,OBOLONJ,PETRIVKA,TARASA_SHEVCHENKO,KONTRAKTOVA_PLOSHCHADJ,POCHTOVAJA_PLOSHCHADJ,
	MAIDAN_NEZALESHNOSTI_P_R,PLOSHCHA_LJVA_TOLSTOGO_P_G,OLIMPIJSKA,PALAZ_UKRAINA,LYBIDSKA,DEMIJIVSKA,GOLOSIJEVSKA,
	VASYLJKIVSKA,VYSTAVKOVYJ_ZENTR,
	
	LISNA,CHERNIGOVSKA,DARNYZJA,LIVOBERESHNA,
	GIDROPARK,DNIPRO,ARSENALJNA,HRESHCHATYK_P_B,TEATRALJNA_P_G,UNIVERSITET,VOKZALJNA,
	POLITEHNICHNYJ_INSTYTUT,SHULJAVSKA,BERESTEJKA,NYVKY,SVJATOSHYNO,SHYTOMYRSKA,ACADEMGORODOK,
	
	CHERVONYJ_HUTIR,BORISPILJSJKA,VYRLYZJA,HARKIVSJKA,POZNJAKY,OSOKORKY,SLAVUTUCH,VYDUBYCHI,DRUSHBY_NARODIV,
	POCHERSKA,KLOVSKA,PALAZ_SPORTU_P_B,ZOLOTI_VOROTA_P_R,LUKJANIVSKA,DOROGOSHYCHI,SYREZJ,
	
	SVJATOSHYNSKO_BROVARSKA_R,SYREZJKO_PECHERSKA_G,KURENJOVSKO_CHERVONOARMEISKA_B,j
	
}
